### ISSUE TITLE
[Crash] Crash w/ the latest IC2C 

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/Advanced-Solars-Classic-Edition#1]
Crash log: https://pastebin.com/QsDQc6mn

Setup:
Minecraft: 1.12.2
Forge:1.12.2-14.23.5.2820
FoamFix: 0.10.5-1.12.2
IC2Classic: 1.12-1.5.4.3
AdvancedSolar: 1.0.1

**Comment by Trinsdar** [comment]
Oh fuck i forgot about this needing to be updated.

**Comment by Trinsdar** [comment]
fixed in 650e183ffda6030663db46935c183484fe8bbf73
