### ISSUE TITLE
[1.19.2] Molecular Transformer Energy Input

### ISSUE THREAD

**Issue by CrossVas** [Trinsdar/Advanced-Solars-Classic-Edition#12]
Currently Molecular Transformer is displaying wrong energy input value for `EU In` in GUI.

With this setup of 2 Ultimate Hybrid Solar Panels, 1024 each, we get `EU In` displaying 1024 instead of 2048 in total.
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/25727222/af8d3421-17d9-4ab5-90af-1253c9d1ebbf)

![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/25727222/bd062d4d-ac27-473c-bf13-ee3a096687cc)

here is the EU-Reader Result:
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/25727222/a82f2fe3-8ed7-4114-a9b7-f41f440923bc)

**Comment by Trinsdar** [comment]
Yah i know about that, not sure what the best way to display it is cause there isn't an easy way to track packets
Edit: just realized the eu reader is tracking it, so nevermind it should be possible

**Comment by Trinsdar** [comment]
fixed in 2.04
