### ISSUE TITLE
[1.19.2] There is no setting for the output from solar panels

### ISSUE THREAD

**Issue by Enroteg** [Trinsdar/Advanced-Solars-Classic-Edition#14]
For solar panels, I can adjust the generation by controlling the multiplier. But by increasing it, I do not increase the output from solar panels. For example, a hybrid solar panel on my server generates 256 EU/t, but the output from it is still 128 EU/t. Also, the output of 128 eu/t is indicated in the wattmeter

**Comment by Trinsdar** [comment]
Fixed in 2.0.5. The tier will now auto adjust based off the production
