### ISSUE TITLE
1.19.2 - Ultimate solar quantum helmet model broken

### ISSUE THREAD

**Issue by NeoFolia** [Trinsdar/Advanced-Solars-Classic-Edition#17]
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/147491823/bc730cd2-9521-41d8-b7f0-494b170a88f5)

**Comment by CrossVas** [comment]
Rename `ultimate_solar_helmet_1` to `ultimate_hybrid_solar_helmet_1` in `assets/advanced_solars/textures/models` and it should be fixed.

[src/main/resources/assets/advanced_solars/textures/models/ultimate_solar_helmet_1.png](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/blob/7652210df1de3fb1a9d47a37a1484c7d4113b5e1/src/main/resources/assets/advanced_solars/textures/models/ultimate_solar_helmet_1.png)

**Comment by Trinsdar** [comment]
I never even noticed this issue, not sure how I missed it

**Comment by Trinsdar** [comment]
Fixed
