### ISSUE TITLE
1.19.2 Molecular Transformer

### ISSUE THREAD

**Issue by atuinilus** [Trinsdar/Advanced-Solars-Classic-Edition#18]
How to remove and add new crafts to molecular transformer on version 1.19.2 via CraftTweaker, and is this possible at the moment?

**Comment by CrossVas** [comment]
New recipes can be added using vanilla datapack system.

Make a datapack.
Create a folder named `molecular_transformer` with the path being `<datapack_name>/data/advanced_solars/ic2_recipes/`, so you want your final path to be:
```
<datapack_name>/data/advanced_solars/ic2_recipes/molecular_transformer
```

Now all you have to do is create json files for each recipe and move them into `molecular_transformer` folder. Here is an example of it:
Using items as input:
```json
{
	"input": {
		"item": "minecraft:dirt",
		"size": 1,
		"type": "ic2:item"
	},
	"output": {
		"item": "minecraft:clay",
		"size": 1,
		"type": "ic2:item"
	},
	"energy": 50000,
	"charging": true,
	"discharging": false
}
```

Using tags as input:
```json
{
	"input": {
		"tag": "forge:storage_blocks/copper",
		"size": 1,
		"type": "ic2:tag"
	},
	"output": {
		"item": "minecraft:diamond",
		"size": 1,
		"type": "ic2:item"
	},
	"energy": 50000,
	"charging": true,
	"discharging": false
}
```

**Comment by atuinilus** [comment]
Thanks a lot
