### ISSUE TITLE
The watt meter does not display the amount of energy in solar panels.

### ISSUE THREAD

**Issue by NeoFolia** [Trinsdar/Advanced-Solars-Classic-Edition#20]
The watt meter does not display the amount of energy in solar panels. When I pick up a watt meter or in a hot bar, I point it at the solar panels from your mod in REI - the energy generation is not shown.

![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/147491823/c810cf11-b19e-411d-a117-5b010ff2192a)
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/147491823/e6d5b540-b82f-4f9e-aa21-8cc190277ec1)

**Comment by Trinsdar** [comment]
fixed in next update
