### ISSUE TITLE
[1.19.2] The output from solar panels does not work correctly

### ISSUE THREAD

**Issue by MegaSusl** [Trinsdar/Advanced-Solars-Classic-Edition#21]
I've adjusted multiplier of solar panels to 4. It generates 4096 EU and it says that max output is 8192. But i can't get more than 1024EU/t out of the panel 
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/126255603/b9425901-32dc-465d-8aab-1f44c66a88a3)
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/126255603/3e3ad0c5-3085-4c12-a089-f7e4dfb60574)
![image](https://github.com/Trins-mods/Advanced-Solars-Classic-Edition/assets/126255603/1bf2b611-c5f8-4909-ac6f-c5ac3b07ee8e)

**Comment by MegaSusl** [comment]
[BlockEntityAdvancedSolarPanel.zip](https://github.com/user-attachments/files/16198760/BlockEntityAdvancedSolarPanel.zip)
My friend and I made some changes here, so maybe you can implement it

**Comment by Trinsdar** [comment]
fixed
